# Site settings
title            : Vincent Knight
email            : vincent.knight@gmail.com
description      : "Class website for my third year Game Theory course. All source files can be found at <a href='https://github.com/drvinceknight/Year_3_game_theory_course'>this github repository</a>."
baseurl          : "/Year_3_game_theory_course"
url              : "http://drvinceknight.github.io"
github_username  : "drvinceknight"
twitter_username : "@drvinceknight"
plus_username    : "+VincentKnight"
blogurl          : "http://drvinceknight.github.io/unpeudemath/"

# Build settings
markdown    : kramdown
permalink   : pretty
highlighter : pygments
